#!/usr/bin/env python

import argparse
import subprocess
import tempfile
import os
import numpy as np



parser = argparse.ArgumentParser()
parser.add_argument("--script", type=str)
parser.add_argument("--job_name", type=str)
parser.add_argument("--core_start", type=int)
parser.add_argument("--core_end", type=int)
parser.add_argument("--script_args", type=str)

args = parser.parse_args()

working_dir = os.getcwd()
script = args.script
script_args = args.script_args
job_name = args.job_name
core_start = args.core_start
core_end = args.core_end

out_dir = os.environ.get("OUT_DIR")
out_file = os.path.join(out_dir, job_name + ".o")
err_file = os.path.join(out_dir, job_name + ".e")
script_full_path = os.path.join(working_dir, script)

command = "nohup taskset --cpu-list %d-%d python %s %s > %s 2> %s &"  % (core_start, core_end, script_full_path, script_args, out_file, err_file)

print(command)
subprocess.run(command, shell=True)
